# OpenCV -Part4

## Find and Draw Contours with OpenCV

<pre>
<b>What are Contours ?</b>
   -> The Curve joining all the continuous points along the boundary which are having the 
      same color or intensity
   -> Contours can be useful tool for Shape Analysis,Object Detection or Object Recognition
   -> For Better accuracy we use binary Image

We will learn to find contours, draw contours, we will see these functions : cv2.findContours(), cv2.drawContours().

</pre>

In [1]:
import cv2
import numpy as np

img=cv2.imread('logo.png')
imgray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#Threshold
_,thresh=cv2.threshold(imgray,127,255,0)

#contours
'''Contours is a Python list of all the contours in the image.
   Each individual contour is a Numpy array of (x,y) coordinates of boundary points of the object'''

contours,hierarchy=cv2.findContours(thresh,mode=cv2.RETR_TREE,method=cv2.CHAIN_APPROX_NONE)
print("Number of Contours "+ str(len(contours)))
print(contours[0])

cv2.drawContours(img,contours,-1,(0,255,198),thickness=3) #-1 = Display all the contours
cv2.imshow('Logo',img)
cv2.imshow('GrayImage',imgray)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

Number of Contours 12
[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]







## Motion Detection and Tracking  
<a href="https://github.com/opencv/opencv/blob/master/samples/data/vtest.avi">Video Link - Click Here to Download</a>

In [1]:
import cv2
import numpy as np

cap = cv2.VideoCapture('vtest.avi')

fourcc =cv2.VideoWriter_fourcc(*'XVID')
out =cv2.VideoWriter("output.avi", fourcc, 5.0, (1280,720))

ret,frame1 = cap.read()
ret,frame2 = cap.read()
print(frame1.shape)

while cap.isOpened():
    diff =cv2.absdiff(frame1, frame2)
    gray =cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
    blur =cv2.GaussianBlur(gray, (5,5), 0)
    _, thresh =cv2.threshold(blur, 20, 255, cv2.THRESH_BINARY)
    dilated =cv2.dilate(thresh, None, iterations=3)
    contours, _ =cv2.findContours(dilated, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

    for contour in contours:
        (x, y, w, h) = cv2.boundingRect(contour)

        if cv2.contourArea(contour) < 800:
            continue
            
        cv2.rectangle(frame1, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(frame1, "Status: {}".format('Movement'), (10, 20), cv2.FONT_HERSHEY_SIMPLEX,
                    1, (0, 0, 255), 3)
    #cv2.drawContours(frame1, contours, -1, (0, 255, 0), 2)

    image = cv2.resize(frame1,(1280,720))
    out.write(image)
    cv2.imshow("Videofeed", frame1)
    frame1 = frame2
    ret,frame2 =cap.read()

    if cv2.waitKey(40)==27:
        break

cv2.destroyAllWindows()
cap.release()
out.release()

(576, 768, 3)
